version: 2.1
jobs:
  compile:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: git clone --quiet -j32 https://github.com/Mhmmdfas/android_kernel_xiaomi_msm8917 --depth=1 -b lineage-17.0 .
      - run: wget https://raw.githubusercontent.com/Mhmmdfas/scripts-build/master/Q/GCC_Q-rolex
      - run: chmod +x GCC_Q-rolex
      - run: bash GCC_Q-rolex
  compiletoo:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: git clone --quiet -j32 https://github.com/Mhmmdfas/android_kernel_xiaomi_msm8917 --depth=1 -b lineage-16.0 .
      - run: wget https://raw.githubusercontent.com/Mhmmdfas/scripts-build/master/Q/GCC_Q-riva
      - run: chmod +x GCC_Q-riva
      - run: bash GCC_Q-riva
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
      - compiletoo
